# Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

# labels to be used with /area command
area:
  - 'kubernetes'
  - 'terraform'
  - 'ansible'
  - 'inspec'
  - 'github'

kind:
  - 'bug'
  - 'documentation'
  - 'discussion'
  - 'feature'
  - 'question'
  - 'support'

priority:
  - backlog
  - 'low'
  - 'medium'
  - 'high'
  - 'critical'

status:
  - available
  - blocked
  - in_progress
  - on_hold

# File globs for PR labeler
# tests:
#   - '**/*.test.ts'

'area/kubernetes':
  - gitops/**/*

'cloud/gcp':
  - terraform/gcp/*
  - terraform/gcp/**/*

'cloud/aws':
  - terraform/aws/*
  - terraform/aws/**/*

'cloud/azure':
  - terraform/azure/*
  - terraform/azure/**/*

'cloud/alicloud':
  - terraform/alicloud/*
  - terraform/alicloud/**/*

'cloud/digitalocean':
  - terraform/digitalocean/*
  - terraform/digitalocean/**/*

'cloud/exoscale':
  - terraform/exoscale/*
  - terraform/exoscale/**/*

'cloud/scaleway':
  - terraform/scaleway/*
  - terraform/scaleway/**/*

'kind/documentation':
  - docs/*
  - docs/**/*
